# -*- coding: utf-8 -*-
"""6h_pm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmX6ZDd8ELKUCPPzpxgD_2frw3JKMiBR
"""

# =========================================================
# PM2.5 6-Hour Forecasting with CatBoostRegressor (Direct Multi-Horizon)
# Reads final CSV, engineers extra features, predicts t+1 ... t+6
# Assumes rows are already sorted chronologically.
# =========================================================

import warnings
warnings.filterwarnings("ignore")

import os
import json
import random
from pathlib import Path

import numpy as np
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


# =========================================================
# CONFIG
# =========================================================
PROJECT_ROOT = Path(__file__).resolve().parents[2]
CSV_PATH = PROJECT_ROOT / "data" / "processed" / "pm25_processed_data.csv"
SOURCE_TARGET_COL = "pm25_avg"
OUTPUT_DIR = PROJECT_ROOT / "notebooks" / "model" / "multi_6h_weights"
TRAIN_DIR = PROJECT_ROOT / "notebooks" / "catboost_info"

RANDOM_SEED = 42
TRAIN_RATIO = 0.70
VALID_RATIO = 0.15
HORIZONS = [1, 2, 3, 4, 5, 6]
CATEGORICAL_COLS = ["Season", "time_of_the_day"]

# Extra feature engineering to add
PM_LAGS_TO_ADD = [2, 3, 4, 5, 12, 18]
PM_ROLL_STD_WINDOWS = [3, 6]
PM_TREND_WINDOWS = [3, 6]

WEATHER_LAG_SPECS = {
    "temperature_2m": [1, 3, 6],
    "relative_humidity_2m": [1, 3, 6],
    "precipitation": [1, 3, 6],
    "wind_speed_10m": [1, 3, 6],
}
WEATHER_ROLL_MEAN_SPECS = {
    "temperature_2m": [3],
    "relative_humidity_2m": [3],
    "wind_speed_10m": [3],
}

USE_LOG_TARGET = False


# =========================================================
# HELPERS
# =========================================================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

def rmse(y_true, y_pred):
    return float(np.sqrt(mean_squared_error(y_true, y_pred)))

def evaluate_horizon(y_true, y_pred):
    return {
        "MAE": float(mean_absolute_error(y_true, y_pred)),
        "MSE": float(mean_squared_error(y_true, y_pred)),
        "RMSE": rmse(y_true, y_pred),
        "R2": float(r2_score(y_true, y_pred)),
    }

def evaluate_all_horizons(y_true_df, y_pred_df, target_cols):
    results = {}
    for col in target_cols:
        results[col] = evaluate_horizon(y_true_df[col], y_pred_df[col])

    y_true_flat = y_true_df[target_cols].values.ravel()
    y_pred_flat = y_pred_df[target_cols].values.ravel()
    results["overall"] = evaluate_horizon(y_true_flat, y_pred_flat)
    return results


# =========================================================
# FEATURE ENGINEERING
# =========================================================
def add_engineered_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    if SOURCE_TARGET_COL not in df.columns:
        raise ValueError(f"Missing required column: {SOURCE_TARGET_COL}")

    for lag in PM_LAGS_TO_ADD:
        col = f"pm25_avg_lag{lag}"
        if col not in df.columns:
            df[col] = df[SOURCE_TARGET_COL].shift(lag)

    for window in PM_ROLL_STD_WINDOWS:
        col = f"pm25_avg_rolling_std_{window}h"
        if col not in df.columns:
            df[col] = df[SOURCE_TARGET_COL].rolling(window=window, min_periods=window).std()

    for window in PM_TREND_WINDOWS:
        col = f"pm25_avg_trend_{window}h"
        if col not in df.columns:
            df[col] = df[SOURCE_TARGET_COL] - df[SOURCE_TARGET_COL].shift(window)

    for base_col, lags in WEATHER_LAG_SPECS.items():
        if base_col in df.columns:
            for lag in lags:
                col = f"{base_col}_lag{lag}"
                if col not in df.columns:
                    df[col] = df[base_col].shift(lag)

    for base_col, windows in WEATHER_ROLL_MEAN_SPECS.items():
        if base_col in df.columns:
            for window in windows:
                col = f"{base_col}_rolling_mean_{window}h"
                if col not in df.columns:
                    df[col] = df[base_col].rolling(window=window, min_periods=window).mean()

    return df


def build_targets(df: pd.DataFrame):
    df = df.copy()
    target_cols = []
    for h in HORIZONS:
        col = f"target_tplus{h}"
        df[col] = df[SOURCE_TARGET_COL].shift(-h)
        target_cols.append(col)
    return df, target_cols


# =========================================================
# DATA PREP
# =========================================================
def load_data(csv_path: str):
    df = pd.read_csv(csv_path).reset_index(drop=True)
    df = add_engineered_features(df)
    df, target_cols = build_targets(df)

    needed_cols = target_cols.copy()
    needed_cols += [SOURCE_TARGET_COL]
    df = df.dropna(subset=needed_cols).copy()
    df = df.dropna().reset_index(drop=True)

    return df, target_cols


def prepare_xy(df: pd.DataFrame, target_cols):
    feature_cols = [c for c in df.columns if c not in target_cols]
    X = df[feature_cols].copy()
    y = df[target_cols].copy()

    cat_cols = [c for c in CATEGORICAL_COLS if c in X.columns]
    for c in cat_cols:
        X[c] = X[c].astype(str)

    if USE_LOG_TARGET:
        y = np.log1p(y)

    return X, y, feature_cols, cat_cols


def time_split(X: pd.DataFrame, y: pd.DataFrame):
    n = len(X)
    train_end = int(n * TRAIN_RATIO)
    valid_end = int(n * (TRAIN_RATIO + VALID_RATIO))

    X_train = X.iloc[:train_end].copy()
    y_train = y.iloc[:train_end].copy()

    X_valid = X.iloc[train_end:valid_end].copy()
    y_valid = y.iloc[train_end:valid_end].copy()

    X_test = X.iloc[valid_end:].copy()
    y_test = y.iloc[valid_end:].copy()

    return X_train, y_train, X_valid, y_valid, X_test, y_test


# =========================================================
# TRAIN
# =========================================================
def train_catboost_multi(X_train, y_train, X_valid, y_valid, cat_cols):
    model = CatBoostRegressor(
        loss_function="MultiRMSE",
        eval_metric="MultiRMSE",
        iterations=2500,
        learning_rate=0.03,
        depth=6,
        l2_leaf_reg=5,
        random_strength=1,
        subsample=0.8,
        bootstrap_type="Bernoulli",
        od_type="Iter",
        od_wait=120,
        random_seed=RANDOM_SEED,
        train_dir=TRAIN_DIR.as_posix(),
        verbose=100
    )

    model.fit(
        X_train,
        y_train,
        cat_features=cat_cols if cat_cols else None,
        eval_set=(X_valid, y_valid),
        use_best_model=True
    )
    return model


# =========================================================
# MAIN
# =========================================================
def main():
    set_seed(RANDOM_SEED)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    TRAIN_DIR.mkdir(parents=True, exist_ok=True)

    df, target_cols = load_data(CSV_PATH)
    X, y, feature_cols, cat_cols = prepare_xy(df, target_cols)
    X_train, y_train, X_valid, y_valid, X_test, y_test = time_split(X, y)

    print("Train:", X_train.shape, y_train.shape)
    print("Valid:", X_valid.shape, y_valid.shape)
    print("Test :", X_test.shape, y_test.shape)
    print("Categorical:", cat_cols)

    model = train_catboost_multi(X_train, y_train, X_valid, y_valid, cat_cols)

    pred = model.predict(X_test)
    pred_df = pd.DataFrame(pred, columns=target_cols, index=y_test.index)

    if USE_LOG_TARGET:
        y_eval = np.expm1(y_test)
        pred_eval = np.expm1(pred_df)
    else:
        y_eval = y_test
        pred_eval = pred_df

    results = evaluate_all_horizons(y_eval, pred_eval, target_cols)

    print("\n===== CatBoost Multi-Horizon Results =====")
    for k, v in results.items():
        print(f"\n{k}")
        for metric_name, metric_val in v.items():
            print(f"  {metric_name}: {metric_val:.6f}")

    with open(OUTPUT_DIR / "metrics.json", "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    pred_out = pred_eval.copy()
    pred_out.columns = [f"pred_{c}" for c in pred_out.columns]
    save_df = pd.concat([y_eval.reset_index(drop=True), pred_out.reset_index(drop=True)], axis=1)
    save_df.to_csv(OUTPUT_DIR / "predictions.csv", index=False)

    fi = pd.DataFrame({
        "feature": feature_cols,
        "importance": model.get_feature_importance()
    }).sort_values("importance", ascending=False)
    fi.to_csv(OUTPUT_DIR / "feature_importance.csv", index=False)

    print("\nTop 25 features:")
    print(fi.head(25).to_string(index=False))


if __name__ == "__main__":
    main()

# import pandas as pd

# # Re-define helper functions and configuration used in the previous cell to ensure correct feature engineering.
# # This is necessary because `df` is not persisted between execution of the main script and new cells.

# CSV_PATH = "pm25_processed_data.csv"
# SOURCE_TARGET_COL = "pm25_avg"

# PM_LAGS_TO_ADD = [2, 3, 4, 5, 12, 18]
# PM_ROLL_STD_WINDOWS = [3, 6]
# PM_TREND_WINDOWS = [3, 6]

# WEATHER_LAG_SPECS = {
#     "temperature_2m": [1, 3, 6],
#     "relative_humidity_2m": [1, 3, 6],
#     "precipitation": [1, 3, 6],
#     "wind_speed_10m": [1, 3, 6],
# }
# WEATHER_ROLL_MEAN_SPECS = {
#     "temperature_2m": [3],
#     "relative_humidity_2m": [3],
#     "wind_speed_10m": [3],
# }

# HORIZONS = [1, 2, 3, 4, 5, 6]

# def add_engineered_features(df: pd.DataFrame) -> pd.DataFrame:
#     df = df.copy()

#     if SOURCE_TARGET_COL not in df.columns:
#         raise ValueError(f"Missing required column: {SOURCE_TARGET_COL}")

#     for lag in PM_LAGS_TO_ADD:
#         col = f"pm25_avg_lag{lag}"
#         if col not in df.columns:
#             df[col] = df[SOURCE_TARGET_COL].shift(lag)

#     for window in PM_ROLL_STD_WINDOWS:
#         col = f"pm25_avg_rolling_std_{window}h"
#         if col not in df.columns:
#             df[col] = df[SOURCE_TARGET_COL].rolling(window=window, min_periods=window).std()

#     for window in PM_TREND_WINDOWS:
#         col = f"pm25_avg_trend_{window}h"
#         if col not in df.columns:
#             df[col] = df[SOURCE_TARGET_COL] - df[SOURCE_TARGET_COL].shift(window)

#     for base_col, lags in WEATHER_LAG_SPECS.items():
#         if base_col in df.columns:
#             for lag in lags:
#                 col = f"{base_col}_lag{lag}"
#                 if col not in df.columns:
#                     df[col] = df[base_col].shift(lag)

#     for base_col, windows in WEATHER_ROLL_MEAN_SPECS.items():
#         if base_col in df.columns:
#             for window in windows:
#                 col = f"{base_col}_rolling_mean_{window}h"
#                 if col not in df.columns:
#                     df[col] = df[base_col].rolling(window=window, min_periods=window).mean()

#     return df

# def build_targets(df: pd.DataFrame):
#     df = df.copy()
#     target_cols = []
#     for h in HORIZONS:
#         col = f"target_tplus{h}"
#         df[col] = df[SOURCE_TARGET_COL].shift(-h)
#         target_cols.append(col)
#     return df, target_cols

# def load_data(csv_path: str):
#     df = pd.read_csv(csv_path).reset_index(drop=True)
#     df = add_engineered_features(df)
#     df, target_cols = build_targets(df)

#     needed_cols = target_cols.copy()
#     needed_cols += [SOURCE_TARGET_COL]
#     df = df.dropna(subset=needed_cols).copy()
#     df = df.dropna().reset_index(drop=True)

#     return df, target_cols


# df, _ = load_data(CSV_PATH)
